apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret
  namespace: dev-ns
spec:
  refreshInterval: 1s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-sample         # name of the SecretStore (or kind specified)
  target:
    # name: google-creds  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: my-api-key  # KSM key name
    remoteRef:
      key: api-secret-dev-stage # name of the GCPSM 
      version: "2"
  # dataFrom:
  # - key: my-secret
  #   version: "18"
  #   property: value-1