apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret
  namespace: stage-ns
spec:
  refreshInterval: 1s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-sample         # name of the SecretStore (or kind specified)
  target:
    name: google-creds  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: my-api-key  # name of the GCPSM secret key
    remoteRef:
      key: api-secret-dev-stage
      version: "3"
  # dataFrom:
  # - key: my-secret
  #   version: "11"
  #   property: name